language: ruby
rvm:
  - 1.9.3
before_script:
  - sudo apt-get update 
  - mysql -e 'create database redminedb;'
  - mysql -e 'create database archiva;'
  - mysql -e 'create database redback;'
  - mysql -e 'create database gerrit;'
  - sudo ./bootstrap.sh
script: ./test/run-tests.sh

