language: ruby
rvm:
  - 1.9.3
before_script:
  - sudo apt-get update 
  - mysql -e 'create database redminedb;'
  - mysql -e 'create database archiva;'
  - mysql -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,INDEX ON archiva.* TO '''archiva'''@'''localhost''' IDENTIFIED BY '''t0rc0zu310''';'
  - mysql -e 'create database redback;'
  - mysql -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,INDEX ON redback.* TO '''archiva'''@'''localhost''' IDENTIFIED BY '''t0rc0zu310''';'
  - mysql -e 'create database gerrit;'
  - mysql -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,INDEX ON gerrit.* TO '''gerrit'''@'''localhost''' IDENTIFIED BY '''t0rc0zu310''';'
  - sudo ./bootstrap.sh
script: ./test/run-tests.sh

