language: ruby
rvm:
  - 1.9.3
before_script:
  - sudo apt-get update 
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('changeme') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - sudo ./bootstrap.sh
script: ./test/run-tests.sh

