#!/bin/bash

# Change these variables to your own values, might be SCSTACK_DIR
servicePath=/home/laforge/scstack-installer/scstack-service

# Don't change the lines below this point
cmd="java -Dfile.encoding=UTF-8 -jar $servicePath/scstack-service.jar"  
# echo -e "Executing command:\n# $cmd"
exec $cmd
